_target_: datamodule.DPRDataModule
max_seq_length: ${max_seq_length}
per_device_train_batch_size: ${per_device_train_batch_size}
per_device_eval_batch_size: ${per_device_eval_batch_size}
test_size: 0.1
num_process: 16
num_workers: 0
seed: ${seed}
