model: # Edit model config referring to the follow link: https://huggingface.co/docs/transformers/master/en/model_doc/auto#transformers.AutoModelForPreTraining
  pretrained_name: "roberta-base"
data:
  data_dir: "datasets/bart" # Fill in the path of a output of running serialize_corpora.py.
  test_size: 0.05 # If you set this argument, arguments must be floating type. (e.g. 0.01)
collator:
  masking_rate: 0.15
training: # Edit training config referring to the follow link: https://huggingface.co/docs/transformers/master/en/main_classes/trainer#transformers.TrainingArguments
  output_dir: "checkpoints/DPRModel" # Fill in the path which is used to save checkpoints.
  overwrite_output_dir: True # If you use multi-node, set this True.
  do_train: True
  do_eval: True
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 1
  learning_rate: 1e-5
  weight_decay: 0.1
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-08
  max_grad_norm: 1.0
  max_steps: 5000
  lr_scheduler_type: "linear"
  warmup_steps: 0
  logging_strategy: "steps"
  logging_steps: 200
  evaluation_strategy: "no"
  eval_steps: 0
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 5
  seed: 42
  fp16: False
  tpu_num_cores: 8
  gradient_checkpointing: False
  